# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
include:
  - board: nice_nano//zmk
    shield: hillside_view_left nice_view_gem
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: hillside_view_right
  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano//zmk
    shield: cygnus_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_USB=n
  - board: nice_nano//zmk
    shield: cygnus_right
    cmake-args: -DCONFIG_ZMK_USB=n
  - board: xiao_ble//zmk
    shield: cygnus_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
